/*!40101 SET NAMES utf8 */;

ALTER TABLE `c_sns_config` ADD COLUMN `color_1` text NOT NULL;
UPDATE `c_sns_config` SET color_1 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_2` text NOT NULL;
UPDATE `c_sns_config` SET color_2 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_3` text NOT NULL;
UPDATE `c_sns_config` SET color_3 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_4` text NOT NULL;
UPDATE `c_sns_config` SET color_4 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_5` text NOT NULL;
UPDATE `c_sns_config` SET color_5 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_6` text NOT NULL;
UPDATE `c_sns_config` SET color_6 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_7` text NOT NULL;
UPDATE `c_sns_config` SET color_7 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_8` text NOT NULL;
UPDATE `c_sns_config` SET color_8 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_9` text NOT NULL;
UPDATE `c_sns_config` SET color_9 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_10` text NOT NULL;
UPDATE `c_sns_config` SET color_10 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_11` text NOT NULL;
UPDATE `c_sns_config` SET color_11 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_12` text NOT NULL;
UPDATE `c_sns_config` SET color_12 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_13` text NOT NULL;
UPDATE `c_sns_config` SET color_13 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_14` text NOT NULL;
UPDATE `c_sns_config` SET color_14 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_15` text NOT NULL;
UPDATE `c_sns_config` SET color_15 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_16` text NOT NULL;
UPDATE `c_sns_config` SET color_16 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_17` text NOT NULL;
UPDATE `c_sns_config` SET color_17 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_18` text NOT NULL;
UPDATE `c_sns_config` SET color_18 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_19` text NOT NULL;
UPDATE `c_sns_config` SET color_19 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_20` text NOT NULL;
UPDATE `c_sns_config` SET color_20 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_21` text NOT NULL;
UPDATE `c_sns_config` SET color_21 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_22` text NOT NULL;
UPDATE `c_sns_config` SET color_22 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_23` text NOT NULL;
UPDATE `c_sns_config` SET color_23 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_24` text NOT NULL;
UPDATE `c_sns_config` SET color_24 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_25` text NOT NULL;
UPDATE `c_sns_config` SET color_25 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_26` text NOT NULL;
UPDATE `c_sns_config` SET color_26 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_27` text NOT NULL;
UPDATE `c_sns_config` SET color_27 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_28` text NOT NULL;
UPDATE `c_sns_config` SET color_28 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_29` text NOT NULL;
UPDATE `c_sns_config` SET color_29 = '000000';
ALTER TABLE `c_sns_config` ADD COLUMN `color_30` text NOT NULL;
UPDATE `c_sns_config` SET color_30 = '000000';

ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_1` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_1 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_2` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_2 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_3` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_3 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_4` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_4 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_5` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_5 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_6` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_6 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_7` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_7 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_8` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_8 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_9` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_9 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_10` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_10 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_11` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_11 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_12` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_12 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_13` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_13 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_14` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_14 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_15` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_15 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_16` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_16 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_17` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_17 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_18` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_18 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_19` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_19 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_20` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_20 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_21` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_21 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_22` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_22 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_23` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_23 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_24` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_24 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_25` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_25 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_26` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_26 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_27` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_27 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_28` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_28 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_29` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_29 = '000000';
ALTER TABLE `c_sns_config_ktai` ADD COLUMN `color_30` text NOT NULL;
UPDATE `c_sns_config_ktai` SET color_30 = '000000';
