UPDATE c_review_category SET category = 'Books' WHERE c_review_category_id = 1;
UPDATE c_review_category SET category = 'ForeignBooks' WHERE c_review_category_id = 2;
UPDATE c_review_category SET category = 'Music' WHERE c_review_category_id = 3;
UPDATE c_review_category SET category = 'Classical' WHERE c_review_category_id = 4;
UPDATE c_review_category SET category = 'DVD' WHERE c_review_category_id = 5;
UPDATE c_review_category SET category = 'VideoGames' WHERE c_review_category_id = 6;
UPDATE c_review_category SET category = 'Software' WHERE c_review_category_id = 7;
UPDATE c_review_category SET category = 'Electronics' WHERE c_review_category_id = 8;
UPDATE c_review_category SET category = 'Kitchen' WHERE c_review_category_id = 9;
UPDATE c_review_category SET category = 'Toys' WHERE c_review_category_id = 10;
UPDATE c_review_category SET category = 'SportingGoods' WHERE c_review_category_id = 11;
UPDATE c_review_category SET category = 'HealthPersonalCare' WHERE c_review_category_id = 12;
INSERT INTO c_review_category VALUES (nextval('c_review_category_c_review_category_id_seq'),'Watches','時計',13);
INSERT INTO c_review_category VALUES (nextval('c_review_category_c_review_category_id_seq'),'Baby','ベビー＆マタニティ',14);
INSERT INTO c_review_category VALUES (nextval('c_review_category_c_review_category_id_seq'),'Apparel','アパレル＆シューズ',15);