UPDATE c_review_category SET category = 'Books' WHERE category = 'books-jp';
UPDATE c_review_category SET category = 'ForeignBooks' WHERE category = 'books-us';
UPDATE c_review_category SET category = 'Music' WHERE category = 'music-jp';
UPDATE c_review_category SET category = 'Classical' WHERE category = 'classical-jp';
UPDATE c_review_category SET category = 'DVD' WHERE category = 'dvd-jp';
UPDATE c_review_category SET category = 'VideoGames' WHERE category = 'videogames-jp';
UPDATE c_review_category SET category = 'Software' WHERE category = 'software-jp';
UPDATE c_review_category SET category = 'Electronics' WHERE category = 'electronics-jp';
UPDATE c_review_category SET category = 'Kitchen' WHERE category = 'kitchen-jp';
UPDATE c_review_category SET category = 'Toys' WHERE category = 'toys-jp';
UPDATE c_review_category SET category = 'SportingGoods' WHERE category = 'sporting-goods-jp';
UPDATE c_review_category SET category = 'HealthPersonalCare' WHERE category = 'hpc-jp';
INSERT INTO c_review_category VALUES (nextval('c_review_category_c_review_category_id_seq'),'Watches','時計',13);
INSERT INTO c_review_category VALUES (nextval('c_review_category_c_review_category_id_seq'),'Baby','ベビー＆マタニティ',14);
INSERT INTO c_review_category VALUES (nextval('c_review_category_c_review_category_id_seq'),'Apparel','アパレル＆シューズ',15);
